apiVersion: v1
kind: Service
metadata:
  name: {{ include "wbsic.fullname" . }}-frontend
  labels:
    {{- include "wbsic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    {{- include "wbsic.selectorLabels" . | nindent 4 }}
    app: frontend